"use strict";

const crypto = require("node:crypto");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { parseListen, parseListenPort } = require("./listen-config.cjs");

function secret() {
  return crypto.randomBytes(32).toString("base64url");
}

function parseEnvFile(text) {
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq < 1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function parseIni(text) {
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#") || trimmed.startsWith(";") || trimmed.startsWith("[")) continue;
    const eq = trimmed.indexOf("=");
    if (eq < 1) continue;
    out[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1);
  }
  return out;
}

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    const token = argv[i];
    if (!token.startsWith("--")) continue;
    const key = token.slice(2);
    const next = argv[i + 1];
    if (!next || next.startsWith("--")) out[key] = "1";
    else {
      out[key] = next;
      i++;
    }
  }
  return out;
}

function upsertEnvKeys(envPath, values) {
  let text = fs.existsSync(envPath) ? fs.readFileSync(envPath, "utf8") : "";
  if (!text.endsWith("\n") && text.length) text += os.EOL;
  for (const [key, value] of Object.entries(values)) {
    if (value == null || value === "") continue;
    const line = `${key}=${value}`;
    const re = new RegExp(`^${key}=.*$`, "m");
    if (re.test(text)) text = text.replace(re, line);
    else text += line + os.EOL;
  }
  fs.writeFileSync(envPath, text, { mode: 0o600 });
}

function writeNewEnv(envPath, opts) {
  const bind = opts.bind || "0.0.0.0";
  const webPort = String(opts.webPort || 3000);
  const agentPort = String(opts.agentPort || 3001);
  const body = [
    "# Generated by the PrivGate installer. Do not commit this file.",
    `SESSION_SECRET=${secret()}`,
    `TICKET_SIGNING_KEY=${secret()}`,
    `DEVICE_SECRET_KEY=${secret()}`,
    "AUTH_MODE=local",
    `PRIVGATE_BIND=${bind}`,
    `PRIVGATE_WEB_PORT=${webPort}`,
    `PRIVGATE_AGENT_PORT=${agentPort}`,
    "# Optional: canonical URLs when the DNS name differs from the listen address.",
    "# PRIVGATE_PUBLIC_ORIGIN=https://privgate.example.com",
    "# PRIVGATE_AGENT_ORIGIN=https://privgate.example.com:3001",
    "",
  ].join(os.EOL);
  fs.writeFileSync(envPath, body, { mode: 0o600 });
}

function writeBootstrap(dir, admin) {
  if (!admin || !admin.email || !admin.password) return false;
  const file = path.join(dir, "bootstrap.json");
  fs.writeFileSync(
    file,
    JSON.stringify({
      email: String(admin.email).trim(),
      password: String(admin.password),
      displayName: String(admin.displayName || admin.name || "").trim(),
    }),
    { mode: 0o600 },
  );
  return true;
}

function applyInstallerConfig(dir, opts = {}) {
  fs.mkdirSync(dir, { recursive: true });
  try {
    fs.chmodSync(dir, 0o700);
  } catch {
    // Windows may reject POSIX modes.
  }
  const envPath = path.join(dir, "console.env");
  const bind = opts.bind;
  const webPort = opts.webPort != null ? String(opts.webPort) : undefined;
  const agentPort = opts.agentPort != null ? String(opts.agentPort) : undefined;
  if (!fs.existsSync(envPath)) {
    writeNewEnv(envPath, { bind, webPort, agentPort });
  } else if (bind || webPort || agentPort) {
    const patch = {};
    if (bind) patch.PRIVGATE_BIND = bind;
    if (webPort) patch.PRIVGATE_WEB_PORT = webPort;
    if (agentPort) patch.PRIVGATE_AGENT_PORT = agentPort;
    upsertEnvKeys(envPath, patch);
  }
  const parsed = parseEnvFile(fs.readFileSync(envPath, "utf8"));
  if (!parsed.AUTH_MODE || parsed.AUTH_MODE === "development") {
    upsertEnvKeys(envPath, { AUTH_MODE: "local" });
  }
  writeBootstrap(dir, opts.admin);
  return envPath;
}

function loadEnvIntoProcess(dir) {
  const envPath = path.join(dir, "console.env");
  if (!fs.existsSync(envPath)) return;
  const parsed = parseEnvFile(fs.readFileSync(envPath, "utf8"));
  for (const [key, value] of Object.entries(parsed)) {
    if (process.env[key] == null || process.env[key] === "") process.env[key] = value;
  }
  process.env.NODE_ENV = process.env.NODE_ENV || "production";
  process.env.PRIVGATE_DATA_DIR = process.env.PRIVGATE_DATA_DIR || dir;
  process.env.PRIVGATE_DB = process.env.PRIVGATE_DB || path.join(dir, "privgate.db");
  const cfg = parseListen(process.env);
  process.env.PRIVGATE_BIND = cfg.bind;
  process.env.PRIVGATE_WEB_PORT = String(cfg.webPort);
  process.env.PRIVGATE_AGENT_PORT = String(cfg.agentPort);
  process.env.PORT = String(cfg.webPort);
  process.env.HOSTNAME = cfg.bind;
  process.env.AUTH_MODE = process.env.AUTH_MODE === "entra" ? "entra" : "local";
}

function optionalPort(raw, fallback) {
  if (raw == null || String(raw).trim() === "") return undefined;
  return parseListenPort(raw, fallback);
}

function fromCli(argv = process.argv.slice(2)) {
  const args = parseArgs(argv);
  let ini = {};
  if (args.ini) ini = parseIni(fs.readFileSync(args.ini, "utf8"));
  const dir = args.dir || args["data-dir"];
  if (!dir) {
    console.error("usage: write-env.cjs --dir <data-dir> [--ini file] [--preserve] [--bind] [--web-port] [--agent-port]");
    process.exit(1);
  }
  const preserve = args.preserve === "1";
  const bind = preserve ? undefined : args.bind || ini.bind;
  const webPort = preserve ? undefined : optionalPort(args["web-port"] || ini.webPort || ini.web_port, 3000);
  const agentPort = preserve ? undefined : optionalPort(args["agent-port"] || ini.agentPort || ini.agent_port, 3001);
  const admin = {
    email: args["admin-email"] || ini.adminEmail || ini.admin_email,
    password: args["admin-password"] || ini.adminPassword || ini.admin_password,
    displayName: args["admin-name"] || ini.adminName || ini.admin_name,
  };
  if (args["admin-password-file"]) {
    admin.password = fs.readFileSync(args["admin-password-file"], "utf8").replace(/\r?\n$/, "");
  }
  applyInstallerConfig(dir, { bind, webPort, agentPort, admin });
  if (args.ini && fs.existsSync(args.ini)) {
    try {
      fs.unlinkSync(args.ini);
    } catch {
      // temp file may already be gone
    }
  }
  console.log(`Wrote ${path.join(dir, "console.env")}`);
}

module.exports = {
  applyInstallerConfig,
  loadEnvIntoProcess,
  parseEnvFile,
  parseIni,
  writeBootstrap,
};

if (require.main === module) fromCli();
